### ISSUE TITLE
Logowanie, wylogowywanie, pamiętanie logowania

### ISSUE THREAD

**Issue by Jerry-BloodBerry** [MikolajczukKamil/inwentaryzacja#134]
Należy zaimplementować w aplikacji te funkcjonalności. Wylogowywanie powinno być dostępne z wielu widoków.

**Comment by StrongMen120** [comment]
Pomoc przybywa Mirek !

**Comment by ghost** [comment]
Jakich dobrych kolegow mam :) Dziekuje bardzo :)
