### ISSUE TITLE
Zapisywanie i odtwarzanie skanowania z bazy BONUS

### ISSUE THREAD

**Issue by MikolajczukKamil** [MikolajczukKamil/inwentaryzacja#159]
Po #158
Jest to zadanie dodatkowe więc nie ma spiny, ale wydaje mi się że to i tak zrobić

**Comment by MikolajczukKamil** [comment]
Cel
Jak przerwiemy skanowanie i odpalimy aplikację od nowa to mamy mieć możliwosć kontynułowania tego skanowania bez utraty dotychczasowej pracy.

Jak to ma działać?
Jak zaczynamy skanowanie (i nie ma niedokończonego) to tworzymy skanowanie na serwerze
Jak już skanujemy to co jakiś czas/za każdą akcją do serwera idzie request z updatem skanowania
co ma taki request? TYLKO ZESKANOWANE itemy (dlaczego? bo np to co ma być może się zmienić do odtworzenia skanowania) assety + stan jest to int co dać konkretnie trzeba przemyśleć aby dało się odtworzyć skanowanie łącznie z np opcją nic nie rób czy dodaj do tej sali.
I wracając do rozpoczynania skanowania jak jest rozpoczęte skanowanie to użytkownik ma mieć możliwość usunięcia jego lub skorzystania jak usunie to wiadomo się usuwa a jak nie to ładujemy skanowanie wg tego co zostało zapisane

**Comment by MikolajczukKamil** [comment]
Za logikę skanowania odpowiadał @RadoslawNagiel

**Comment by Jerry-BloodBerry** [comment]
@dzaleski jak tam postępy w tym zadaniu?
