### ISSUE TITLE
Testy jednostkowe

### ISSUE THREAD

**Issue by MikolajczukKamil** [MikolajczukKamil/inwentaryzacja#161]
Można a nawet należy zacząć testowanie komponentów oraz apicontrollera oraz działających komponentów
rzeczy jakie trzeba koniecznie przetestować to zachowanie komponentów na błędy w api (zwraca np nulla i wywołuje Event z błędem) czy wtedy komponent się nie wywala
Jak by były problemy z przetestowaniem niektórych komponentów należy się zwrócić do ich autorów o należyte poprawki

**Comment by MiiiZawadzki** [comment]
Biorę Region "Report" do testowania ApiController

**Comment by CaptSarge** [comment]
Biorę region "Localization" do testowania ApiController

**Comment by sawitom** [comment]
Biorę region "Scanning" do testowania ApiController
