### ISSUE TITLE
Scenariusze testowe 

### ISSUE THREAD

**Issue by MikolajczukKamil** [MikolajczukKamil/inwentaryzacja#174]
Wymagania podlegające ocenie

3 Scenariusze testowe Ocena opracowanych scenariuszy testowych

**Comment by martamazurkiewicz** [comment]
Funkcjonalności:
1.	Logowanie (zrobione)
2.	Wylogowanie
3.	Wybranie raportu po nazwie
4.	Przejrzenie raportu 
5.	Wybór Sali w której jest inwentaryzacja
6.	Skanowanie
7.	Przeniesienie środka trwałego gdy należy do innej sali
a)	Przeniesienie wszystkich środków trwałych
8.	Nie przeniesienie środka trwałego, gdy należy do innej Sali (odniesienie środka do macierzystej Sali)
9.	Przerwanie skanowania w trakcie jego wykonywania

**Comment by MiiiZawadzki** [comment]
Jeżeli te funkcjonalności są wolne, to ja wybieram: 2,3,4.

**Comment by CaptSarge** [comment]
Wybieram 5, 6, 7

**Comment by sawitom** [comment]
Biorę 8,9
