### ISSUE TITLE
Diagramy czynności i przypadków użycia

### ISSUE THREAD

**Issue by Jerry-BloodBerry** [MikolajczukKamil/inwentaryzacja#175]
Należy dokonać poprawki diagramu czynności oraz wykonać diagram przypadków użycia dla aplikacji.

Jeśli chodzi o diagram czynności to tu jest jego pierwowzór:
![obraz](https://user-images.githubusercontent.com/45820576/83351394-b8fdd280-a343-11ea-85fd-224a7101fe6a.png)

**Comment by MikolajczukKamil** [comment]
https://drive.google.com/drive/folders/1U_ifo9VkDklahk1UcBDfhspYLdueSvNd?usp=sharing
Tu plik z schematem
Dla przypomnienia na któryś zajęciach dr omawiał schemat i mówił co należy poprawić

**Comment by MikolajczukKamil** [comment]
Gdzie to umieścić?
Proponuję nowy branch od mastera `schematy` i tak elegancko je umieścić

**Comment by Jerry-BloodBerry** [comment]
Jak postępy w tym zadaniu?

**Comment by zniwek** [comment]
![APKA DIAGRAMY vpd](https://user-images.githubusercontent.com/62554037/83641481-e51c8c00-a5ad-11ea-86f6-bfd7e4610549.png)

Diagram czynności

**Comment by zniwek** [comment]
![APKA DIAGRAMY2 vpd](https://user-images.githubusercontent.com/62554037/83643624-89073700-a5b0-11ea-91c1-415e86868fa4.png)

Diagram przypadków użycia

**Comment by Jerry-BloodBerry** [comment]
Myślę, że dobrze. @martamazurkiewicz czy to Ci wystarczy?

Żeby nie było: Mirek, robisz własne diagramy. Te powstały, żeby Marta miała więcej czasu na swoje zadanie.

**Comment by zniwek** [comment]
Po lekkich poprawkach, diagramy użycia i czynności 
![APKA DIAGRAMY USE2](https://user-images.githubusercontent.com/62554037/83742603-ea371500-a659-11ea-8bd9-5a3413afd692.png)
![APKA DIAGRAMYv8 vpd](https://user-images.githubusercontent.com/62554037/83742604-eacfab80-a659-11ea-89d5-46cdfd404d74.png)

**Comment by ghost** [comment]
![Untitled Diagram vpd](https://user-images.githubusercontent.com/62663042/84444617-de93b180-ac4a-11ea-9a27-7ac2ffcdaf7a.jpg)

**Comment by ghost** [comment]
Jak by tak wyglądał UML, było by ok ?

**Comment by ghost** [comment]
![czyn vpd](https://user-images.githubusercontent.com/62663042/84447685-5cf35200-ac51-11ea-9a2b-d0953b5c5691.jpg)
