### ISSUE TITLE
Diagramy UML

### ISSUE THREAD

**Issue by Jerry-BloodBerry** [MikolajczukKamil/inwentaryzacja#176]
- [x] Należy wykonać diagramy klas UML dla aplikacji.

- [ ] Oprócz tego trzeba pousuwać nieużywane klasy z aplikacji, bo trochę ich się nagromadziło. Nie ma sensu, żeby zaśmiecały nam projekt.

**Comment by MikolajczukKamil** [comment]
Nieużywane klasy mamy tu na myśli przede wszystkim Klasy typu `Room`, gdyż one miały być używane przez aplikację ale większość korzysta od razu z `RoomEntity` (Encje z bazy) i tak główne klasy i Serwisy zrobiły się zbędne
