### ISSUE TITLE
Po dodaniu nowego budynku, aplikacja łapie błąd

### ISSUE THREAD

**Issue by MikolajczukKamil** [MikolajczukKamil/inwentaryzacja#181]
System.ArgumentOutOfRangeException: 'Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index'

**Comment by Jerry-BloodBerry** [comment]
Problem leży w tym fragmencie kodu: 
![obraz](https://user-images.githubusercontent.com/45820576/83512728-f17ee700-a4d0-11ea-9117-e284dbf94633.png)
Ponieważ Maciek i Daniel wprowadzali zmiany ostatnio to proszę o zbadanie sprawy.
