### ISSUE TITLE
APIController poprawki

### ISSUE THREAD

**Issue by MikolajczukKamil** [MikolajczukKamil/inwentaryzacja#187]
Poprawić APIController:
`createReport()` powinno zwracać id utworzonego raportu, -1 jak się nie udało
`createBuilding()`, `createRoom()` tak samo, choć to ma mniejszy priorytet bo jako tako działa
`CreateAsset()` usunąć, nie ma to sensu nie pomyślałem o tym wcześniej :D aplikacja nie ma takiej opcji (przynajmniej nie ma w planach)

Dodać obsługę skanowań:
adekwatne metody do następujących endpointów: getScans, addScan, deleteScan, updateScan

Dodawanie zwraca obiekt `{ id: int|null, message: null|string }` (id lub message jest nullem, id == null -> nie udało się wtedy message jest springiem z informacją o błędzie) - w razie problemów trzeba się zwrócić z prośbą podmiany np id na -1 zamiast null czy "" zamiast null w message

**Comment by Jerry-BloodBerry** [comment]
Maćku, endpointy do skanowań po stronie API są już gotowe. Zostało zaktualizować kontroler. Jeśli pojawią się błędy, albo pytania do API to pisz, odpowiem możliwie najszybciej
