### ISSUE TITLE
Komunikat o braku pomieszczeń w danym budynku

### ISSUE THREAD

**Issue by MikolajczukKamil** [MikolajczukKamil/inwentaryzacja#200]
Jeżeli w wybranym budynku nie ma żadnego pomieszczenia wybór sali nie reaguje i ma się wrażenie że coś nie działa, trzeba dodać w takim przypadku komunikat o tym że pomieszczeniu nie ma żadnej sali, w postaci tekstu bądź alerta jak uznasz że będzie lepiej

**Comment by dzaleski** [comment]
dodałem pull request #203
