### ISSUE TITLE
Ikona i nazwa dla aplikacji

### ISSUE THREAD

**Issue by MikolajczukKamil** [MikolajczukKamil/inwentaryzacja#206]
Maciek zrobił logo przy starcie aplikacji, fajnie to wygląda tylko na razie jest tam logo i napis xamarin, dobrze by było znaleźć jakąś fajną ikonkę i ją tam wykorzystać + dać ją jako główną ikonę aplikacji przy okazji dać nazwę aplikacji na razie jest Inwentaryzacja.Android, jako nazwa chyba wystarczy po prostu "Inwentaryzacja" .
Ikona może być podobna do ikony skanowania która już występuje w aplikacji tylko w kolorze
Podrzucam przykładową stronkę z wieloma również darmowymi ikonkami https://www.flaticon.com/

![btnimg](https://user-images.githubusercontent.com/25321219/84139301-e89d9080-aa4f-11ea-9579-a4139944a02f.png)

**Comment by Grzybojad** [comment]
![Ikona_inwentaryzacja](https://user-images.githubusercontent.com/18161644/84250210-092b2080-ab0c-11ea-89a1-7a67a48c0f93.png)

Może być? @MikolajczukKamil

**Comment by MikolajczukKamil** [comment]
Piękna ikona :D

**Comment by Jerry-BloodBerry** [comment]
@StrongMen120 możesz podpatrzeć jak Maciek niedawno ustawił ikonkę i nazwę i na tej podstawie to zrobić 😄

**Comment by StrongMen120** [comment]
jutro to ogarnę
