### ISSUE TITLE
Zadanie - widok Powitania (programmers)

### ISSUE THREAD

**Issue by Jerry-BloodBerry** [MikolajczukKamil/inwentaryzacja#62]
Należy utworzyć widok Powitania jako stronę zawartości (Content Page) GreetingsPage.xaml zgodnie z projektem widoku, który zamieszczam poniżej:
![obraz](https://user-images.githubusercontent.com/45820576/78291909-7af05800-7526-11ea-9db6-160569afc765.png)

**Comment by MikolajczukKamil** [comment]
Specjalnie dla @Miraslauzbarouski
