### ISSUE TITLE
Wykonać API

### ISSUE THREAD

**Issue by MikolajczukKamil** [MikolajczukKamil/inwentaryzacja#90]
Komunikacja z bazą - prosta nakładka
technologia dowolna możne być czysty PHP może być dowolny framweork

Ważne: Musi sprawdzać użytkownika - nie zalogowany = nic nie może zrobić

**Comment by MikolajczukKamil** [comment]
#91 Tu zadanie na logowanie użytkownika, będzie to mocno skorelowane

**Comment by maciek1651g** [comment]
Nie wiem czy podołam temu zadaniu, więc zapraszam również inne osoby do niego.

**Comment by Jerry-BloodBerry** [comment]
Też nad tym pracuję, więc możemy połączyć siły :)
