### ISSUE TITLE
Problem z widokiem skanowania

### ISSUE THREAD

**Issue by Jerry-BloodBerry** [MikolajczukKamil/inwentaryzacja#93]
Po kliknięciu w przycisk "Podgląd" pojawia się błąd tego rodzaju (różnie jest on formułowany w zależności od używanej wersji API):

```
System.InvalidOperationException
  Message=PushAsync is not supported globally on Android, please use a NavigationPage.
```

![obraz](https://user-images.githubusercontent.com/45820576/79880275-153e1000-83f0-11ea-9607-4a83c0a39d14.png)

**Comment by Jerry-BloodBerry** [comment]
Maćku czy to zostało rozwiązane?

**Comment by maciek1651g** [comment]
Jeśli przechodzenie na stronę skanowania będzie wykonane z użyciem NavigationPage, to wszystko będzie działać. Nie ma się czym przejmować. 

A jeśli ktoś chce zobaczyć jak to działa to musi w pliku App.xaml.cs wpisać: MainPage = new NavigationPage(new ScanItemPage());
