### ISSUE TITLE
APIController

### ISSUE THREAD

**Issue by MikolajczukKamil** [MikolajczukKamil/inwentaryzacja#96]
Zrobić obsługę API, proponuję aby każdy endpooint miał metodę do jego obsłużenia, tu sama obsługa co z tymi danymi zrobić wiedzą odpowiednie serwisy

https://github.com/Jerry-BloodBerry/InwentaryzacjaAPI

**Comment by maciek1651g** [comment]
Mogę z tych metod zwrócić już stringa z danymi w JSON, czy zwrócić cały obiekt HttpResponseMessage
